version: '3.5'

services:
  
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./init-db/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: venom
      DB_USER: venom
      DB_PASS: venom
      DB_NAME: venom
      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9000:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
